name: Post-merge

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build --release
